"""init schema

Revision ID: 463753819845
Revises: 
Create Date: 2026-07-04 02:08:19.358344
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '463753819845'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=120), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('website_url', sa.String(length=1000), nullable=True),
    sa.Column('google_place_id', sa.String(length=255), nullable=True),
    sa.Column('google_rating', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('discovery_provider', sa.String(length=50), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('DISCOVERED', 'VALIDATED', 'AUDITED', 'ARCHIVED', name='business_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'google_place_id', name='uq_business_org_place')
    )
    op.create_index(op.f('ix_businesses_category'), 'businesses', ['category'], unique=False)
    op.create_index(op.f('ix_businesses_city'), 'businesses', ['city'], unique=False)
    op.create_index(op.f('ix_businesses_name'), 'businesses', ['name'], unique=False)
    op.create_index(op.f('ix_businesses_organization_id'), 'businesses', ['organization_id'], unique=False)
    op.create_index(op.f('ix_businesses_website_url'), 'businesses', ['website_url'], unique=False)
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'key', name='uq_setting_org_key')
    )
    op.create_index(op.f('ix_settings_organization_id'), 'settings', ['organization_id'], unique=False)
    op.create_table('audit_jobs',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='audit_status'), nullable=False),
    sa.Column('current_stage', sa.String(length=50), nullable=True),
    sa.Column('failed_stage', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_jobs_business_id'), 'audit_jobs', ['business_id'], unique=False)
    op.create_index(op.f('ix_audit_jobs_organization_id'), 'audit_jobs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_audit_jobs_status'), 'audit_jobs', ['status'], unique=False)
    op.create_table('users',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'ANALYST', 'VIEWER', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_table('accessibility_findings',
    sa.Column('audit_job_id', sa.UUID(), nullable=False),
    sa.Column('missing_alt_count', sa.Integer(), nullable=True),
    sa.Column('heading_hierarchy_issues', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('aria_issues', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('contrast_issues', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('unlabeled_buttons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('keyboard_nav_issues', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('unlabeled_form_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('accessibility_score', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['audit_job_id'], ['audit_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accessibility_findings_audit_job_id'), 'accessibility_findings', ['audit_job_id'], unique=False)
    op.create_table('ai_reports',
    sa.Column('audit_job_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=True),
    sa.Column('technical_summary', sa.Text(), nullable=True),
    sa.Column('business_summary', sa.Text(), nullable=True),
    sa.Column('seo_summary', sa.Text(), nullable=True),
    sa.Column('accessibility_summary', sa.Text(), nullable=True),
    sa.Column('security_summary', sa.Text(), nullable=True),
    sa.Column('design_summary', sa.Text(), nullable=True),
    sa.Column('top_improvements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('estimated_effort', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('priority_fixes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('estimated_business_impact', sa.Text(), nullable=True),
    sa.Column('markdown_storage_path', sa.String(length=1000), nullable=True),
    sa.Column('html_storage_path', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['audit_job_id'], ['audit_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_reports_audit_job_id'), 'ai_reports', ['audit_job_id'], unique=False)
    op.create_table('campaigns',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('stage', sa.Enum('DISCOVERED', 'AUDITED', 'EMAIL_DRAFTED', 'SENT', 'OPENED', 'CLICKED', 'RESPONDED', 'MEETING_SCHEDULED', 'CLOSED_WON', 'CLOSED_LOST', 'ARCHIVED', name='campaign_stage'), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('next_follow_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_business_id'), 'campaigns', ['business_id'], unique=False)
    op.create_index(op.f('ix_campaigns_organization_id'), 'campaigns', ['organization_id'], unique=False)
    op.create_index(op.f('ix_campaigns_stage'), 'campaigns', ['stage'], unique=False)
    op.create_table('job_events',
    sa.Column('audit_job_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('STARTED', 'SUCCEEDED', 'FAILED', 'RETRIED', name='job_event_status'), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('model_used', sa.String(length=120), nullable=True),
    sa.Column('tokens_input', sa.Integer(), nullable=True),
    sa.Column('tokens_output', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('memory_mb', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['audit_job_id'], ['audit_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_events_audit_job_id'), 'job_events', ['audit_job_id'], unique=False)
    op.create_index(op.f('ix_job_events_stage'), 'job_events', ['stage'], unique=False)
    op.create_table('lead_scores',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('audit_job_id', sa.UUID(), nullable=False),
    sa.Column('performance_component', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('security_component', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('accessibility_component', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('seo_component', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('design_component', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('business_rating_component', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('review_count_component', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('website_age_component', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('technology_component', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('overall_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='lead_priority'), nullable=False),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['audit_job_id'], ['audit_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_scores_audit_job_id'), 'lead_scores', ['audit_job_id'], unique=False)
    op.create_index(op.f('ix_lead_scores_business_id'), 'lead_scores', ['business_id'], unique=False)
    op.create_index(op.f('ix_lead_scores_overall_score'), 'lead_scores', ['overall_score'], unique=False)
    op.create_index(op.f('ix_lead_scores_priority'), 'lead_scores', ['priority'], unique=False)
    op.create_table('lighthouse_reports',
    sa.Column('audit_job_id', sa.UUID(), nullable=False),
    sa.Column('raw_json_storage_path', sa.String(length=1000), nullable=False),
    sa.Column('performance_score', sa.Integer(), nullable=True),
    sa.Column('accessibility_score', sa.Integer(), nullable=True),
    sa.Column('seo_score', sa.Integer(), nullable=True),
    sa.Column('best_practices_score', sa.Integer(), nullable=True),
    sa.Column('lcp_ms', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cls', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('speed_index_ms', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tti_ms', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fcp_ms', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['audit_job_id'], ['audit_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lighthouse_reports_audit_job_id'), 'lighthouse_reports', ['audit_job_id'], unique=False)
    op.create_table('outreach_emails',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('audit_job_id', sa.UUID(), nullable=True),
    sa.Column('template_key', sa.String(length=120), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Enum('DRAFTED', 'APPROVED', 'SENT', 'FAILED', name='email_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audit_job_id'], ['audit_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outreach_emails_business_id'), 'outreach_emails', ['business_id'], unique=False)
    op.create_table('security_findings',
    sa.Column('audit_job_id', sa.UUID(), nullable=False),
    sa.Column('https', sa.Boolean(), nullable=True),
    sa.Column('tls_version', sa.String(length=20), nullable=True),
    sa.Column('cert_issuer', sa.String(length=255), nullable=True),
    sa.Column('cert_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hsts', sa.Boolean(), nullable=True),
    sa.Column('csp', sa.Text(), nullable=True),
    sa.Column('permissions_policy', sa.Text(), nullable=True),
    sa.Column('referrer_policy', sa.Text(), nullable=True),
    sa.Column('x_frame_options', sa.Text(), nullable=True),
    sa.Column('x_content_type_options', sa.Text(), nullable=True),
    sa.Column('cookie_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mixed_content', sa.Boolean(), nullable=True),
    sa.Column('directory_listing_exposed', sa.Boolean(), nullable=True),
    sa.Column('exposed_source_maps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('exposed_config_files', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('exposed_secrets_regex_hits', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tech_fingerprint', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('server_header', sa.Text(), nullable=True),
    sa.Column('compression', sa.Text(), nullable=True),
    sa.Column('caching_headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('public_api_endpoints', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('manifest_present', sa.Boolean(), nullable=True),
    sa.Column('service_worker_present', sa.Boolean(), nullable=True),
    sa.Column('hygiene_score', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['audit_job_id'], ['audit_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_findings_audit_job_id'), 'security_findings', ['audit_job_id'], unique=False)
    op.create_table('website_snapshots',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('audit_job_id', sa.UUID(), nullable=False),
    sa.Column('final_url', sa.String(length=1000), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('redirect_chain', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('html_storage_path', sa.String(length=1000), nullable=True),
    sa.Column('robots_txt', sa.Text(), nullable=True),
    sa.Column('sitemap_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('favicon_url', sa.String(length=1000), nullable=True),
    sa.Column('nav_structure', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('forms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('buttons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fonts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('js_files', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('css_files', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('crawled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['audit_job_id'], ['audit_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_website_snapshots_audit_job_id'), 'website_snapshots', ['audit_job_id'], unique=False)
    op.create_index(op.f('ix_website_snapshots_business_id'), 'website_snapshots', ['business_id'], unique=False)
    op.create_table('campaign_events',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_events_campaign_id'), 'campaign_events', ['campaign_id'], unique=False)
    op.create_table('screenshots',
    sa.Column('website_snapshot_id', sa.UUID(), nullable=False),
    sa.Column('device', sa.Enum('DESKTOP', 'TABLET', 'MOBILE', name='device_type'), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['website_snapshot_id'], ['website_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screenshots_website_snapshot_id'), 'screenshots', ['website_snapshot_id'], unique=False)
    op.create_table('vision_analyses',
    sa.Column('audit_job_id', sa.UUID(), nullable=False),
    sa.Column('screenshot_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('trust_score', sa.Integer(), nullable=True),
    sa.Column('professionalism_score', sa.Integer(), nullable=True),
    sa.Column('modernity_score', sa.Integer(), nullable=True),
    sa.Column('whitespace_score', sa.Integer(), nullable=True),
    sa.Column('typography_score', sa.Integer(), nullable=True),
    sa.Column('layout_score', sa.Integer(), nullable=True),
    sa.Column('visual_hierarchy_score', sa.Integer(), nullable=True),
    sa.Column('cta_score', sa.Integer(), nullable=True),
    sa.Column('conversion_score', sa.Integer(), nullable=True),
    sa.Column('brand_consistency_score', sa.Integer(), nullable=True),
    sa.Column('nav_clarity_score', sa.Integer(), nullable=True),
    sa.Column('mobile_friendliness_score', sa.Integer(), nullable=True),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['audit_job_id'], ['audit_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['screenshot_id'], ['screenshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vision_analyses_audit_job_id'), 'vision_analyses', ['audit_job_id'], unique=False)
    op.create_index(op.f('ix_vision_analyses_screenshot_id'), 'vision_analyses', ['screenshot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vision_analyses_screenshot_id'), table_name='vision_analyses')
    op.drop_index(op.f('ix_vision_analyses_audit_job_id'), table_name='vision_analyses')
    op.drop_table('vision_analyses')
    op.drop_index(op.f('ix_screenshots_website_snapshot_id'), table_name='screenshots')
    op.drop_table('screenshots')
    op.drop_index(op.f('ix_campaign_events_campaign_id'), table_name='campaign_events')
    op.drop_table('campaign_events')
    op.drop_index(op.f('ix_website_snapshots_business_id'), table_name='website_snapshots')
    op.drop_index(op.f('ix_website_snapshots_audit_job_id'), table_name='website_snapshots')
    op.drop_table('website_snapshots')
    op.drop_index(op.f('ix_security_findings_audit_job_id'), table_name='security_findings')
    op.drop_table('security_findings')
    op.drop_index(op.f('ix_outreach_emails_business_id'), table_name='outreach_emails')
    op.drop_table('outreach_emails')
    op.drop_index(op.f('ix_lighthouse_reports_audit_job_id'), table_name='lighthouse_reports')
    op.drop_table('lighthouse_reports')
    op.drop_index(op.f('ix_lead_scores_priority'), table_name='lead_scores')
    op.drop_index(op.f('ix_lead_scores_overall_score'), table_name='lead_scores')
    op.drop_index(op.f('ix_lead_scores_business_id'), table_name='lead_scores')
    op.drop_index(op.f('ix_lead_scores_audit_job_id'), table_name='lead_scores')
    op.drop_table('lead_scores')
    op.drop_index(op.f('ix_job_events_stage'), table_name='job_events')
    op.drop_index(op.f('ix_job_events_audit_job_id'), table_name='job_events')
    op.drop_table('job_events')
    op.drop_index(op.f('ix_campaigns_stage'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_organization_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_business_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_ai_reports_audit_job_id'), table_name='ai_reports')
    op.drop_table('ai_reports')
    op.drop_index(op.f('ix_accessibility_findings_audit_job_id'), table_name='accessibility_findings')
    op.drop_table('accessibility_findings')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_audit_jobs_status'), table_name='audit_jobs')
    op.drop_index(op.f('ix_audit_jobs_organization_id'), table_name='audit_jobs')
    op.drop_index(op.f('ix_audit_jobs_business_id'), table_name='audit_jobs')
    op.drop_table('audit_jobs')
    op.drop_index(op.f('ix_settings_organization_id'), table_name='settings')
    op.drop_table('settings')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_businesses_website_url'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_organization_id'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_name'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_city'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_category'), table_name='businesses')
    op.drop_table('businesses')
    # ### end Alembic commands ###
