"""add technical findings and page load time

Revision ID: 6eb9808ba5be
Revises: f02952f2526a
Create Date: 2026-07-08 08:51:17.758891
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '6eb9808ba5be'
down_revision: Union[str, None] = 'f02952f2526a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('technical_findings',
    sa.Column('audit_job_id', sa.UUID(), nullable=False),
    sa.Column('page_load_time_ms', sa.Float(), nullable=True),
    sa.Column('sitemap_present', sa.Boolean(), nullable=True),
    sa.Column('robots_present', sa.Boolean(), nullable=True),
    sa.Column('favicon_present', sa.Boolean(), nullable=True),
    sa.Column('schema_markup_present', sa.Boolean(), nullable=True),
    sa.Column('schema_markup_valid', sa.Boolean(), nullable=True),
    sa.Column('open_graph_present', sa.Boolean(), nullable=True),
    sa.Column('twitter_card_present', sa.Boolean(), nullable=True),
    sa.Column('google_business_link', sa.String(length=1000), nullable=True),
    sa.Column('broken_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('broken_links_count', sa.Integer(), nullable=True),
    sa.Column('oversized_images', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('oversized_images_count', sa.Integer(), nullable=True),
    sa.Column('technical_score', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['audit_job_id'], ['audit_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technical_findings_audit_job_id'), 'technical_findings', ['audit_job_id'], unique=False)
    op.add_column('website_snapshots', sa.Column('page_load_time_ms', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('website_snapshots', 'page_load_time_ms')
    op.drop_index(op.f('ix_technical_findings_audit_job_id'), table_name='technical_findings')
    op.drop_table('technical_findings')
    # ### end Alembic commands ###
