"""add contact fallback fields

Revision ID: f02952f2526a
Revises: 463753819845
Create Date: 2026-07-03 18:47:44.264141
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f02952f2526a'
down_revision: Union[str, None] = '463753819845'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('businesses', sa.Column('facebook_url', sa.String(length=1000), nullable=True))
    op.add_column('businesses', sa.Column('instagram_url', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'instagram_url')
    op.drop_column('businesses', 'facebook_url')
    op.drop_column('businesses', 'email')
    # ### end Alembic commands ###
